name: eve-kernel build
on:
  pull_request_review:
    types: [submitted]
  push:
    branches:
      - "eve-kernel-amd64-v6.1.38-generic"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  packages:
    runs-on: self-hosted
    steps:
      - name: Get eve-kernel
        uses: actions/checkout@v3
        with:
          ref: "eve-kernel-amd64-v6.1.38-generic"
      - name: Always build eve-kernel-amd64
        run: |
          make -f Makefile.eve BRANCH?=${GITHUB_REF##*/} kernel-gcc
      - name: Log in to Docker Hub
        if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.RELEASE_DOCKERHUB_ACCOUNT }}
          password: ${{ secrets.RELEASE_DOCKERHUB_TOKEN }}
      - name: Push eve-kernel-amd64-v6.1.38-generic if PR approved
        if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved'
        run: |
          make -f Makefile.eve BRANCH?=${GITHUB_REF##*/} push-gcc
